# Generated by Django 5.1.2 on 2024-11-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_got',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
